### ISSUE TITLE
I cannot decrypt my encrypted files

### ISSUE THREAD

**Issue by salamsoliman** [njordhov/dcrypt#1]
I encrypted files on your site, and downloaded those files with .dcrypt format. And tried to decrypt on the next step, but the button "Save Decrypted File" doesn't work.

the console errors:

Uncaught TypeError: Cannot read property 'replace' of undefined
    at O (Dropzone.jsx:25)
    at Decrypt.jsx:96
    at FileReader.<anonymous> (Decrypt.jsx:23)

**Comment by njordhov** [comment]
Thank you for reporting this issue. I really appreciate your feedback. It has been fixed in the latest update. Please do not hesitate to let me know if you encounter anything else.
